### PR TITLE
remove from server_instances to force login in next cycle

### PR DESCRIPTION
**Pull request by ahalam**
We discovered that a read timeout results in session timeout. The server_instance is invalid. See https://jira.nutanix.com/browse/ENG-377380?focusedCommentId=3436751&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3436751. Therefore we need to re-login. Therefore by deleting the server_instance from the dict, we will force _get_server_instance() to SmartConnect again in the next cycle.

### CODE REVIEW

**Comment by bhowmickatish** [comment]
replicate the same in _collect_non_metric_mors_and_attributes

**Comment by ahalam** [comment]
> replicate the same in _collect_non_metric_mors_and_attributes

I do not have access to i_key in those functions. This function is anyway called periodically so automatic recovery will happen.

**Comment by ahalam** [comment]
@bhowmickatish I have only removed the session from the dict. I have not terminated using pyvmomi. Will this be a resource leak?

**Comment by bhowmickatish** [comment]
> @bhowmickatish I have only removed the session from the dict. I have not terminated using pyvmomi. Will this be a resource leak?

yes i think so not becoz of leak but internally the connection object is cached until disconnected , so we probably hv to call disconnect explicitly to clear the cache

**Comment by bhowmickatish** [comment]
we probably shud add a delete_server_instance(instance) method to the Class & use it in the exception handlers as required . If that needs change of arguments in some method like _collect_non_metric_mors_and_attributes so be it. Probably better to pass instance to these methods instead of server_instance so that if needed delete can be called.

**Comment by bhowmickatish** [comment]
> > replicate the same in _collect_non_metric_mors_and_attributes
> 
> I do not have access to i_key in those functions. This function is anyway called periodically so automatic recovery will happen.

session can get invalidated anytime , so better to invoke the delete_server_instance in both handlers to make sure connection is reestablished in next iteration of collection.

**Comment by ahalam** [comment]
Closing this because https://github.com/netsil/integrations-core/pull/61 supercedes it.

**Pull request closed without merging**
